---
name: Run Python Tests

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest -v

  install:
    name: Run install.sh and verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run install script (non-interactive)
        run: |
          yes '' | bash scripts/install.sh

      - name: Verify installation
        run: |
          set -euo pipefail
          test -x "$HOME/Jarvis/.venv/bin/jarvis"
          
